config/routes.rb
Rails.application.routes.draw do

  
  

  resources :done_lessons
  get 'admin/index'

  resources :line_items
  resources :inventories
  get 'store/index'

  resources :items
  resources :characters do
    collection do
      post :addItem
      post :removeItem
    end
  end

  resources :lessons
  resources :store
  
  get 'main/index'

  get 'quiz/index'

  get 'quiz/gerar_quiz'

  get 'quiz/catalog'

  resources :quiz do
    collection do
      post :answer
    end
  end

  devise_for :users, controllers: {registrations: "registrations"}

  resources :questions

  root 'main#index'

end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :User
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]
  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.where(User_id: current_user)
    @inventories = Inventory.where(User_id: current_user)
  end

  def addItem
    item_name = params[:item_name]
    item_img = params[:item_img]
    item_part = params[:part]
    @character = Character.where(User_id: current_user).first
    if item_part == "helmet"
      @character.helmet = item_img
    elsif item_part == "shield"
      @character.shield = item_img
    elsif item_part == "weapon"
      @character.weapon = item_img
    elsif item_part == "armor"
      @character.armor = item_img            
    end  
    
    if @character.save
    redirect_to :action => :index
    end
  end

  def removeItem
    item_part = params[:part]
    @character = Character.where(User_id: current_user).first
    if item_part == "helmet"
      @character.helmet = "none"
    elsif item_part == "shield"
      @character.shield = "none"
    elsif item_part == "weapon"
      @character.weapon = "none"
    elsif item_part == "armor"
      @character.armor = "none"            
    end  


    if @character.save
    redirect_to :action => :index
    end
  end  
  # GET /characters/1
  # GET /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @characters = Character.where(User_id: current_user)
    if(@characters.size >= 1)
      redirect_to characters_url
    else  
      @character = Character.new
    end  
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @inventory = Inventory.new
    @inventory.User_id = current_user.id
    @character = Character.new(character_params)
    @character.User_id = current_user.id
    @character.level = 1
    @character.xp = 0
    @character.gold = 200
    @character.helmet = "none"
    @character.armor = "none"
    @character.weapon = "none"
    @character.shield = "none"
    @character.wrong = 0
    @character.correct = 0
    respond_to do |format|
      if @character.save && @inventory.save
        format.html { redirect_to characters_url, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @done_lessons = DoneLesson.where(character_id: @character.id)
    @done_lessons.each do |done_lesson|
      done_lesson.destroy
    end  
    @character.destroy
    @inventories = Inventory.where(User_id: current_user)
    @inventories.each do |inventory|
      inventory.destroy
    end  
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:name, :xp, :gold, :hair, :skin, :shirt, :pants, :User_id)
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% @character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :xp %><br>
    <%= f.number_field :xp %>
  </div>
  <div class="field">
    <%= f.label :gold %><br>
    <%= f.number_field :gold %>
  </div>
  <div class="field">
    <%= f.label :hair %><br>
    <%= f.text_field :hair %>
  </div>
  <div class="field">
    <%= f.label :skin %><br>
    <%= f.text_field :skin %>
  </div>
  <div class="field">
    <%= f.label :shirt %><br>
    <%= f.text_field :shirt %>
  </div>
  <div class="field">
    <%= f.label :pants %><br>
    <%= f.text_field :pants %>
  </div>
  <div class="field">
    <%= f.label :User_id %><br>
    <%= f.text_field :User_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<h2 class="text-center">Seu Personagem</h2>

<div class="container">
<br>
<div class="row">
  <div role="main" class="col-md-3 thumbnail col-char">

    <%if @characters.size >= 1%>
    <% @characters.each do |character| %>
    <h2><%= character.name %></h2>
    <h3>Level: <%= character.level %></h3>
    <h3>xp: <%= character.xp %></h3>
    <h3>Gold: <%= character.gold %></h3>
  </div>
  <div class="col-md-1 col-char">
    
  </div>
  
  <aside role="complementary" class="col-md-8 col-char">
  <h3>Inventario: </h3>
  <%= link_to image_tag("bag.png", :border => 0, :class => 'list_image'), inventories_url %>
  <div id="canvasDiv"></div>
    <script type="text/javascript">
    prepareCanvas(document.getElementById("canvasDiv"), 490, 220, "<%= @character.helmet%>", "<%= @character.armor%>", "<%= @character.shield%>", "<%= @character.weapon%>");
    change('hair', "<%= character.hair %>");
    change('torso', "<%= character.shirt %>");
    change('legs', "<%= character.pants %>");
    if("<%= character.skin %>" != "default"){
    change('head', "head_" + "<%= character.skin %>");
    change('leftArm', "leftArm_" + "<%= character.skin %>");
    change('rightArm', "rightArm_" + "<%= character.skin %>");
    }
    </script>
    <%= link_to 'Deletar', character, method: :delete, data: { confirm: 'Cuidado, tem certeza que quer deletar seu personagem?' }, class: "btn btn-danger" %>
    <br><br>
    <% end %>
    <% else %>
    <h2>Voce ainda não tem um personagem</h2>
    <%= link_to 'New Character', new_character_path %>
    <% end %>
    </aside>
</div>
</div>

app/views/characters/new.html.erb
<br><br><h2 class="text-center">Criar Personagem</h2><br><br><br>

<div class="container">
  <div class="row-fluid">


    <div class="col-md-7">
      <div id="canvasDiv"></div>
        <script type="text/javascript">
         prepareCanvas(document.getElementById("canvasDiv"), 490, 220, "none", "none", "none", "none");
        </script> 
      </div> 
    </div> 

    <%= form_for(@character) do |f| %>

      <div class="col-md-5">

        <div class="field input-group">
          <span class="input-group-addon" id="basic-addon1"><%= f.label :Nome %></span>
          <%= f.text_field :name, :class => 'form-control'%>
          <br>
        </div>

        <br><br>
        <div class="row-fluid text-center">

          <div class="media">
            <div class="media-left">                
              <%= image_tag  "sm_hair.png", :class =>"media-left"%>
            </div>
            <div class="media-body">
              <div id="hair_div">
                <%#= f.label :hair %>
                <%= f.radio_button :hair, 'hair', onClick: "change('hair', 'hair');", :checked => true %> 
                <%= label :hair_default, 'Default'%>
                <%= f.radio_button :hair, 'hair_green', onClick: "change('hair','hair_green');" %>
                <%= label :hair_green, 'Green' %>
                <%= f.radio_button :hair, 'hair_pink', onClick: "change('hair','hair_pink');"%> 
                <%= label :hair_blue, 'Pink' %>
                <%= f.radio_button :hair, 'hair_red', onClick: "change('hair','hair_red');" %>
                <%= label :hair_brown, 'Red' %>
                <%= f.radio_button :hair, 'hair_yellow', onClick: "change('hair','hair_yellow');" %>
                <%= label :hair_yellow, 'yellow' %>
              </div>
            </div>
            <hr>

            <div class="media-left">                
              <%= image_tag  "sm_torso.png", :class =>"media-left"%>
            </div>
            <div class="media-body">
              <div id="shirt_div">
                <%= f.radio_button :shirt, 'torso', onClick: "change('torso', 'torso');", :checked => true %> 
                <%= label :torso, 'Default'%>
                <%= f.radio_button :shirt, 'torso_blue', onClick: "change('torso','torso_blue');" %>
                <%= label :shirt_blue, 'Blue' %>
                <%= f.radio_button :shirt, 'torso_gray', onClick: "change('torso','torso_gray');"%> 
                <%= label :shirt_gray, 'Gray' %>
                <%= f.radio_button :shirt, 'torso_purple', onClick: "change('torso','torso_purple');" %>
                <%= label :shirt_purple, 'Purple' %>

              </div>
            </div>
            <hr>

            <div class="media-left">                
              <%= image_tag  "sm_head.png", :class =>"media-left"%>
            </div>
            <div class="media-body">
               <div id="skin_div">
                <%= f.radio_button :skin, 'default', onClick: "change('head', 'head');change('leftArm', 'leftArm');change('rightArm', 'rightArm');", :checked => true %> 
                <%= label :skin, 'Default'%>
                <%= f.radio_button :skin, 'green', onClick: "change('head', 'head_green');change('leftArm', 'leftArm_green');change('rightArm', 'rightArm_green');" %>
                <%= label :skin, 'Green' %>
                <%= f.radio_button :skin, 'pink', onClick: "change('head', 'head_pink');change('leftArm', 'leftArm_pink');change('rightArm', 'rightArm_pink');"%> 
                <%= label :skin, 'Pink' %>
                <%= f.radio_button :skin, 'yellow', onClick: "change('head', 'head_yellow');change('leftArm', 'leftArm_yellow');change('rightArm', 'rightArm_yellow');" %>
                <%= label :skin, 'Yellow' %>
              </div>
            </div>
            <hr>

            <div class="media-left">                
              <%= image_tag  "sm_legs.png", :class =>"media-left"%>
            </div>
            <div class="media-body">
              <div id="pants">
              <%= f.radio_button :pants, 'legs', onClick: "change('legs', 'legs');", :checked => true %> 
              <%= label :pants, 'Default'%>
              <%= f.radio_button :pants, 'legs_gray', onClick: "change('legs', 'legs_gray');" %>
              <%= label :pants, 'Gray' %>
              <%= f.radio_button :pants, 'legs_green', onClick: "change('legs', 'legs_green');"%> 
              <%= label :skin, 'Green' %>
              </div>
            </div>

            <br><br>
            <div class="btn-group actions">
              <%= f.submit "Criar Personagem", :class=>"btn-group btn btn-info"%>
            </div>
              
          </div><!--media-->
        </div><!--row-->
        <br><br>
      </div>

    <% end %>
  </div>
</div>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Xp:</strong>
  <%= @character.xp %>
</p>

<p>
  <strong>Gold:</strong>
  <%= @character.gold %>
</p>

<p>
  <strong>Hair:</strong>
  <%= @character.hair %>
</p>

<p>
  <strong>Skin:</strong>
  <%= @character.skin %>
</p>

<p>
  <strong>Shirt:</strong>
  <%= @character.shirt %>
</p>

<p>
  <strong>Pants:</strong>
  <%= @character.pants %>
</p>

<p>
  <strong>User:</strong>
  <%= @character.User %>
</p>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>