config/routes.rb
Rails.application.routes.draw do

  
  

  resources :done_lessons
  get 'admin/index'

  resources :line_items
  resources :inventories
  get 'store/index'

  resources :items
  resources :characters do
    collection do
      post :addItem
      post :removeItem
    end
  end

  resources :lessons
  resources :store
  
  get 'main/index'

  get 'quiz/index'

  get 'quiz/gerar_quiz'

  get 'quiz/catalog'

  resources :quiz do
    collection do
      post :answer
    end
  end

  devise_for :users, controllers: {registrations: "registrations"}

  resources :questions

  root 'main#index'

end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :User
end

app/models/done_lesson.rb
class DoneLesson < ActiveRecord::Base
  belongs_to :Lesson
  belongs_to :Character
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  belongs_to :User
  has_many :line_items, dependent: :destroy
end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :line_items
	before_destroy :ensure_not_referenced_by_any_line_item

	private
	def ensure_not_referenced_by_any_line_item
	if line_items.empty?
	return true
	else
	errors.add(:base, 'Line Items present')
	return false
	end
	end
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :Item
  belongs_to :Inventory
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :inventory
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable, :timeoutable
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  before_action :admin_check
  # GET /lessons
  # GET /lessons.json
    def admin_check

    if current_user.admin == false

      redirect_to main_index_path

    end


  end
  
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:url, :subject)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index

    if user_signed_in? && current_user.admin == true

      redirect_to admin_index_url

    elsif user_signed_in?
      	  
    	#

    else

      redirect_to new_user_session_path

    end


  end
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController



  def index
    @characters = Character.where(User_id: current_user)
    if(@characters.size >= 1)
  	   @lesson = Lesson.new(lesson_params)
  	   @video = @lesson.url
  	   @questions = Question.where(lesson: @lesson.subject).order("RANDOM()").limit(5)
    else
      redirect_to characters_url
    end
  end

  def catalog
    @character = Character.where(User_id: current_user).first
    @done_lessons = DoneLesson.where(character_id: @character.id)
  end  
  
  def gerar_quiz
  	
  end

  def answer
    @answer1 = params[:answer1]
    @answer2 = params[:answer2]
    @answer3 = params[:answer3]
    @answer4 = params[:answer4]
    @answer5 = params[:answer5]  
    @statement1 = params[:statement1]
    @statement2 = params[:statement2]
    @statement3 = params[:statement3]
    @statement4 = params[:statement4]
    @statement5 = params[:statement5]
    @question1 = Question.where(statement: @statement1).first
    @question2 = Question.where(statement: @statement2).first
    @question3 = Question.where(statement: @statement3).first
    @question4 = Question.where(statement: @statement4).first
    @question5 = Question.where(statement: @statement5).first
    @answers = [@answer1, @answer2, @answer3, @answer4, @answer5]
    @lesson = Lesson.where(subject: @question1.lesson).first
    @character = Character.where(User_id: current_user).first
    @win = false
    @questions_answers = [@question1.a, @question2.a, @question3.a, @question4.a, @question5.a] 
    @result = 0

    for i in 0..4 do
      if (@answers[i] == @questions_answers[i])
         @result = @result + 1
      end  
    end  

    @done_lessons = DoneLesson.where("lesson_id = ? AND character_id = ?", @lesson.id, @character.id).order(id: :asc).first 

    if @done_lesson == nil
      @done_lesson = DoneLesson.new
      @done_lesson.Lesson_id = @lesson.id
      @done_lesson.Character_id = @character.id
      @done_lesson.score = @result
      @done_lesson.save
      @xp_mult = @result * 10
      @gold_mult = @result * 5 
      @character.correct += @result
      @character.wrong += 5 - @result
      @character.xp += @xp_mult
      @character.gold += @gold_mult
      @win = true
    if @character.xp >= 200 
      @character.xp = 0
      @character.level += 1
    end
      @character.save
    elsif @done_lesson.score < @result
      @done_lesson.score = @result  
      @done_lesson.save
      @xp_mult = @result * 10
    @gold_mult = @result * 5 
    @character.correct += @result
    @character.wrong += 5 - @result
    @character.xp += @xp_mult
    @character.gold += @gold_mult
    @win = true
    if @character.xp >= 200 
      @character.xp = 0
      @character.level += 1
    end
      @character.save
    end
    

  end  

  def lesson_params
      params.permit(:subject, :url)
  end

  
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/done_lessons_helper.rb
module DoneLessonsHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/lessons/_form.html.erb
<%= form_for(@lesson) do |f| %>
  <% if @lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% @lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form' %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<div class="panel panel-default">
<div class="panel-heading">Aulas</div>
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Url</th>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.url %></td>
        <td><%= lesson.subject %></td>
        <td><%= link_to 'Show', lesson %></td>
        <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
        <td><%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
<%= link_to 'Nova aula', new_lesson_path, class: 'btn btn-primary'%>
</div>
<br>


<br><br>
</div>

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form' %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @lesson.url %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @lesson.subject %>
</p>

<%= link_to 'Edit', edit_lesson_path(@lesson) %> |
<%= link_to 'Back', lessons_path %>